/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projet_Sup;

import CLassesSupp.Employe;
import CLassesSupp.Rayon;
import CLassesSupp.Secteur;
import CLassesSupp.Travailler;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Dell
 */
public class frmAutre extends javax.swing.JFrame {
  ArrayList<Secteur> mesSecteurs= new ArrayList<>();
  Vector v;
  DefaultTableModel dtmRayon;
  DefaultTableModel dtmEmployes;
  DefaultTableModel dtmSecteurs;
  
    /**
     * Creates new form frmAutre
     */
    public frmAutre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRayons = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSecteurs = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEmployes = new javax.swing.JTable();
        lblTempsMoyenTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblRayons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRayons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRayonsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRayons);

        tblSecteurs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSecteurs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSecteursMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSecteurs);

        tblEmployes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOM", "TEMPS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmployes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblEmployes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTempsMoyenTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 61, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblTempsMoyenTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        dtmSecteurs = (DefaultTableModel) tblSecteurs.getModel();
        dtmRayon = (DefaultTableModel) tblRayons.getModel();
        dtmEmployes = (DefaultTableModel) tblEmployes.getModel();
        
        Secteur sec1 = new Secteur(1,"Multimédia");
        Secteur sec2 = new Secteur(2,"Electroménager");
       
        
        
        Rayon ray1 = new Rayon (1,"télévision");
        Rayon ray2 = new Rayon (2,"informatique");
        Rayon ray3 = new Rayon (3,"Lave vaisselle");
        
        
        
        
        Employe emp1 = new Employe(1,"Marie");
        Employe emp2 = new Employe(2,"stéphanie");
        Employe emp3 = new Employe(3,"Karim");
        Employe emp4 = new Employe(4,"Pierre");
        Employe emp5 = new Employe(5,"Lucile");
        
        Travailler trav1 = new Travailler(emp1,4);
        Travailler trav2 = new Travailler(emp2,8);
        Travailler trav3 = new Travailler(emp3,1);
        Travailler trav4 = new Travailler(emp4,5);
        Travailler trav5 = new Travailler(emp5,6);
        Travailler trav6 = new Travailler(emp1,8);
        Travailler trav7 = new Travailler(emp2,3);
        
        ray1.getLesTravailler().add(trav1);
        ray1.getLesTravailler().add(trav2);
        ray2.getLesTravailler().add(trav3);
        ray2.getLesTravailler().add(trav4);
        ray3.getLesTravailler().add(trav5);
        ray3.getLesTravailler().add(trav6);
        ray3.getLesTravailler().add(trav7);

        
        sec1.getLesRayons().add(ray1);
        sec1.getLesRayons().add(ray2);
        sec2.getLesRayons().add(ray3);
        
        
        mesSecteurs.add(sec1);
        mesSecteurs.add(sec2);
        
        int tempsTotal=0;
        int nbEmployes=0;
        
        for(Secteur sec : mesSecteurs)   
        {
            v=new Vector();
            v.add(sec.getIdSecteur());
            v.add(sec.getNomSecteur());
            dtmSecteurs.addRow(v);
            
            for (Rayon ray : sec.getLesRayons())
            {
                for(Travailler trav : ray.getLesTravailler())
                {
                    tempsTotal=tempsTotal + trav.getTempsPasse();
                    nbEmployes++;
                }
            }
        }
        
        double res = (double)tempsTotal / nbEmployes;
        
        //Pour transformer en chaine de caractere
        lblTempsMoyenTotal.setText(String.valueOf(res));
        
        
       
               
    }//GEN-LAST:event_formWindowOpened

    private void tblSecteursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSecteursMouseClicked
        // TODO add your handling code here:
        
        //Pour effacer avant dafficher une autre ligne selectionne
        dtmRayon.getDataVector().removeAllElements();
        //getValueAt = Pour recuperer la valeur demander
        String nomSecteur;
        nomSecteur=tblSecteurs.getValueAt(tblSecteurs.getSelectedRow(),1).toString();
        
       for(Secteur sec : mesSecteurs)
        {
            if(sec.getNomSecteur().compareTo(nomSecteur)==0)
            {
                for(Rayon ray : sec.getLesRayons())
                {
                    v = new Vector();
                    v.add(ray.getIdRayon());
                    v.add(ray.getNomRayon());
                    dtmRayon.addRow(v);
                    
                }
            }
        }
    }//GEN-LAST:event_tblSecteursMouseClicked

    private void tblRayonsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRayonsMouseClicked
        // TODO add your handling code here:
    dtmEmployes.getDataVector().removeAllElements();
        for(Secteur sec : mesSecteurs)
        {
            for(Rayon ray : sec.getLesRayons())
            {
                if(ray.getIdRayon()==Integer.parseInt(tblRayons.getValueAt(tblRayons.getSelectedRow(),0).toString()))
                {
                    for (Travailler trav : ray.getLesTravailler())
                    {
                        v= new Vector();
                        v.add(trav.getUnEmploye().getIdEmploye());
                        v.add(trav.getUnEmploye().getNomEmploye());
                        v.add(trav.getTempsPasse());
                        dtmEmployes.addRow(v);
                    }
                    
                }
            }
        }
    }//GEN-LAST:event_tblRayonsMouseClicked

    private void tblEmployesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployesMouseClicked
        // TODO add your handling code here:
        String nomEmploye = tblEmployes.getValueAt(tblEmployes.getSelectedRow(),1).toString();
        int tempsTotal=0;
        int nbFois=0;
        
        for (Secteur sec : mesSecteurs)
        {
            for (Rayon ray : sec.getLesRayons())
            {
                for (Travailler trav : ray.getLesTravailler())
                {
                    if (trav.getUnEmploye().getNomEmploye().compareTo(nomEmploye)==0)
                    {
                        tempsTotal=tempsTotal + trav.getTempsPasse();
                        nbFois = nbFois + 1;
                    }
                }
            }
        }
        JOptionPane.showMessageDialog(this,nomEmploye + " a travaillé " + String.valueOf((double)tempsTotal / nbFois+ "heures"));
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_tblEmployesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAutre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAutre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAutre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAutre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAutre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTempsMoyenTotal;
    private javax.swing.JTable tblEmployes;
    private javax.swing.JTable tblRayons;
    private javax.swing.JTable tblSecteurs;
    // End of variables declaration//GEN-END:variables
}
